# （一）前置准备

## 1. 实例对象与函数对象

- 函数对象: 将函数作为对象使用时, 简称为函数对象
- 实例对象: `new` 函数产生的对象, 称为实例对象，简称为对象

```js
function Fn() { }

let fn = new Fn()
console.log(fn)
console.log(Fn.prototype)
console.log(Fn.bind())
```
输出：
```
Fn {}
{}
[Function: bound Fn]
```

`fn` 是通过 `new` 构造函数的形式产生的对象，所以 `fn` 是实例对象。`Fn` 是 `function` 定义的，所以 `Fn` 是函数，同时，`Fn` 具有 `prototype` 属性，按照语法格式说明 `Fn` 也是一个对象，所以 `Fn` 是一个函数对象。

## 2. 两种回调函数

### 2.1 理解

回调函数：函数被作为实参传入另一函数，并在该外部函数内被调用，用以来完成某些任务的函数，称为回调函数。

- 同步回调
  - 理解: 立即执行, 完全执行完了才结束，不会放入回调队列中
  - 例子: 数组遍历相关的回调函数 / Promise的excutor函数
- 异步回调: 
  - 理解: 不会立即执行，会放入回调队列中将来执行
  - 例子: 定时器回调 / ajax回调 / Promise的成功|失败的回调

### 2.2 举例

**同步回调举例**

```js
function hello(s) {
  console.log(s)
}
function say(callback) {
  console.log('say hello')
  callback('hello')
}
say(hello)
```
输出：
```
say hello
hello
```
回调函数就是把函数作为参数，然后再当前函数执行完后，再执行的函数。同步回调就是当前函数执行完后，会立即执行内部的回调函数。

**异步回调举例**

```js
setTimeout(() => {
  console.log(2)
}, 0)
console.log(1)
```

这里的 `setTimeout` 接收一个箭头函数作为参数，形成了回调函数，而且是异步回调。异步回调函数不会立即执行，而是先放在一个回调队列中，后面才会执行。所以结果如下：
```
1
2
```

## 3. Error 对象

ECMA-262 规范了 7 种错误类型，具体说明如下。其中 `Error` 是基类，其他 6 种错误类型是子类，都继承 `Error` 基类。`Error` 类型的主要用途是自定义异常对象。

`Error` 创建自定义异常:
```js
new Error([message])
```

内置的错误类型，继承自 `Error`：
- `Error`：普通异常。与 `throw` 语句和 `try/catch` 语句一起使用，`message` 属性可以读写详细错误信息。
- `EvalError`：不正确的使用 `eval()` 方法时抛出。
- `SyntaxError`：出现语法错误时抛出。
- `RangeError`：数字超出合法范围时抛出、
- `ReferenceError`：读取不存在的变量时抛出，无效引用。
- `TypeError`：变量或参数不属于有效类型。
- `URIError`：URI 编码和解码错误时抛出。例如，给 `encodeURI()` 或 `decodeURI()` 传递的参数无效。

使用 `try/catch/finally` 可以捕获并处理异常，具体请查看：
https://docs.mphy.top/#/JavaScript/ch13